site_name: HySim

nav:
  - Home: index.md
  - Installation: 'installation.md'
  - 'User Guide':
    - 'Configuring a case': 'user_guide/configuring.md'
    - 'Preparing a target mesh': 'user_guide/mesh_prep.md'
    - 'Running a case': 'user_guide/running.md'
    - 'Advanced use cases': 'user_guide/advanced.md'
  - 'Example Cases':
    - 'TerraSAR Flyby': 'example_cases/terrasar_case.md'
    - 'ISS Flyby': 'example_cases/iss_case.md'
  - 'About':
    - ''
    - 'Licence': 'licence.md'
theme:
    name: material
    palette:
      scheme: default
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
