site_name: HySim

# =========================================
# Contents
nav:
  - Home: index.md
  - Installation: 'installation.md'
  - 'User Guide':
    - 'Configuring a case': 'user_guide/configuring.md'
    - 'Preparing a target mesh': 'user_guide/mesh_prep.md'
    - 'Running a case': 'user_guide/running.md'
    - 'Advanced use cases': 'user_guide/advanced.md'
  - 'Example Cases':
    - 'TerraSAR Flyby': 'example_cases/terrasar_case.md'
    - 'ISS Flyby': 'example_cases/iss_case.md'
  - 'About':
    - ''
    - 'Licence': 'licence.md'

# =========================================
# Theme
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.tabs.link

# =========================================
# Plugins & Extensions
plugins:
  - search
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
